import Head from 'next/head';
import Base from '../components/Base';
import Header from '../components/Header';

interface IMyWrap {
    children: JSX.Element;
    title: string;
}

const MyWrap = ({ children, title }: IMyWrap) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
            </Head>

            <div className="container" id="app">
                <Header/>
                <Base children={children}/>
            </div>
        </>
    )
}

export default MyWrap;
